# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: kphetdev
google_analytics: kphetdev
title: kphetdev

# Google Analytics
google_analytics: UA-113900166-1

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: kphetdev

description: Personal modern programming note, tutorial and walkthrough
author:
  name: Kphetdev
  email: xprimo10@gmail.com
  github: kphetdev
  bio: Sharing modern programming note
  email_md5: b45ea792b55275e56ea796614219658a

categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate